# Inleiding

De studie van historische dakconstructies in hout is een volwaardig onderdeel van architectuur-historisch onderzoek[^inleiding-1]. Dakkappen bieden niet alleen een inzicht in de evolutie van houtbouw en het timmermansambacht, ze laten ook een beter begrip toe van de geschiedenis van een gebouw. De dakkap vormt doorgaans het sluitstuk van een ruwbouwfase. Bij latere uitbreiding of aanpassing van het gebouw blijft de originele dakkap soms integraal onderdeel uitmaken van het gerenoveerde gebouw. In andere gevallen wordt een nieuwe kap opgetrokken, waarbij mogelijk het oudere bouw-hout (gedeeltelijk) wordt gerecupereerd. De dakkap refereert daardoor steeds naar het originele ontwerp of een ingrijpende bouwfase van een gebouw. De datering van een dakkap vormt aldus een ankerpunt in de bouwgeschiedenis en is onlosmakelijk verbonden met het optrekken van muurwerk of de bouwfasering.

[^inleiding-1]: Janse & Devliegher 1962; Hoffsummer 2002, 2009.

Voor oude dakconstructies biedt de binnenstad van Brugge een onvergelijkbaar onderzoeks-potentieel. Dankzij de uitzonderlijk goede bewaring van het historisch stadslandschap vindt men in Brugge nog talrijke dakkappen uit de middeleeuwen en nieuwe tijd. Deze inventaris van historische kappen in de Reiestad biedt aldus een uniek overzicht van zes eeuwen dakenbouw in de welomschreven geografische en historische ruimte van één enkele stad. Er is hierbij geen voorkeur gegeven aan bepaalde types van gebouwen; in deze inventaris zijn kappen opgenomen van kerken, openbare gebouwen (hallen, hospitalen) en burgerhuizen. Als een inventaris van constructies die niet zichtbaar zijn van op het openbaar domein vormt deze catalogus een aanvulling en uitdieping van de inventaris van het bouwkundig erfgoed *Bouwen door de eeuwen heen* voor de historische stadskern van Brugge, waarin gebouwen hoofdzakelijk worden beschreven op basis van de zichtbare buiten-gevels[^inleiding-2]. Al biedt deze catalogus zeker geen exhaustief overzicht, en zal deze ongetwijfeld nog verder aangevuld worden met nieuwe ontdekkingen, toch heeft dit onderzoek van oude kappen in Brugge nogmaals aangetoond dat achter historische gevels vaak nog veel oudere constructies kunnen schuilgaan.

[^inleiding-2]: Online: https://inventaris.onroerenderfgoed.be/

Tijdens deze inventarisatie van middeleeuwse dakkappen in Brugge, werd dankbaar gebruik gemaakt van dendrochronologisch onderzoek. De houten elementen van de onderzochte dakkappen vormen immers het uitgelezen onderzoeksmateriaal voor jaarringanalyse. De resultaten van een dendro-chronologisch onderzoek laten in de eerste plaats toe de dakconstructies exact te dateren, waardoor men zeer nauwkeurig kan bepalen wanneer een gebouw of een deel ervan onder dak werd gebracht. Ook latere herstellingen of hergebruik van oudere materialen zijn met behulp van deze daterings-techniek te detecteren. Bovendien kan ook het herkomstgebied van het bouwhout nader bepaald worden, wat in een ruimere context ook een inkijk biedt op de socio-economische organisatie en handelsbetrekkingen die nodig waren om het nodige bouwmateriaal aan te voeren.

Deze geïntegreerde aanpak, waarin bouwhistorisch en dendrochronologische onderzoek elkaar aanvullen en sturen, laat toe de historische context waarin een gebouw tot stand kwam beter te begrijpen. Dit maakt een precieze omschrijving van de erfgoedwaarde mogelijk en, finaal, laat het toe een gefundeerde motivatie voor de wettelijk beschermde status van een gebouw te onderbouwen.
