# Hout en baksteen

Een dakconstructie staat niet op zichzelf maar is een essentieel onderdeel van een gebouw. Wanneer gedateerd - door dendrochronologie, geschreven bronnen of bouwhistorische vergelijking - biedt zij dan ook uiterst waardevolle inzichten in de geschiedenis van een gebouw. Als na bouwhistorisch onderzoek blijkt dat de dakkap inderdaad gelijktijdig is met het onderliggende metselwerk, dan kan men via deze omweg chronologieën opstellen van bouwmaterialen en bouwtechnieken. Het grote aantal middeleeuwse kappen in Brugge met een nauwkeurige dendrochronologische datering maakt de opmaak mogelijk van een lokale chronologie van baksteenmetselwerk (baksteenformaten, metselverbanden, tienlagenmaten) in de 13de en 14de eeuw[^hout-1]. Deze chronologie, die nog altijd wordt aangevuld en verfijnd, kan op haar beurt worden gebruikt om kappen die dendrochronologisch niet dateerbaar zijn, toch enigszins binnen een bepaald tijdvak te situeren. Zo hebben ook enkele kappen in deze catalogus, ondanks het ontbreken van een dendrochronologische datering, toch een - weliswaar ruime - datering gekregen. Waar relevant is in de beschrijving van de dakkap het baksteenformaat van het onderliggende metselwerk opgenomen, met vermelding van de lengte en de hoogte (bijvoorbeeld: 30 x 6 cm), of indien opgemeten ook de breedte (genoteerd als L x B x H).

[^hout-1]: Debonne 2015.

Kwaliteitsvol eikenhout, zonder al teveel spinthout dat makkelijk door insecten wordt aangevreten, blijft in droge omstandigheden eeuwenlang zijn sterkte-eigenschappen behouden. Bij afbraak of vervanging van een bestaande kap komt een grote hoeveelheid constructiehout beschikbaar dat in dergelijke gevallen perfect kan hergebruikt worden. Achteraf valt het hergebruik van ouder bouwhout in een meer recente constructie echter te herkennen. In de nieuwe houtconstructie zijn dan elementen te onderscheiden met uitsparingen of de profilering van een houtverbinding die niet langer functioneel is. Bijvoorbeeld bij hergebruikte sporen of kepers die oorspronkelijk halfhouts met elkaar waren verbonden, of waar een korbeel of standzoon via een pen-en-gat verbinding aan was vast gemaakt. In de nieuwe constructie zijn op deze hergebruikte elementen dan insparingen te zien of pengaten die geen duidelijke functie of relatie met de nieuwere constructie hebben (zie bijvoorbeeld figuur 4 en figuur 26, een windschoor met meerdere niet langer functionele pengaten uit de dakkap van het huis aan Kraanplein 4).

Hergebruik kan soms ook aangetoond worden door dendrochronologisch onderzoek. De datering van hergebruikt materiaal zal een (sterk) afwijkende (oudere) kapdatum hebben in vergelijking met bouwhout uit dezelfde kap dat wel pas werd aangekocht of gekapt ten tijde van de opbouw. De kap boven het middenkoor van de Onze-Lieve-Vrouwhemelvaartkerk in Damme is hiervan een voorbeeld. Indien een kap volledig uit hergebruikt materiaal is opgetrokken is dit uiteraard niet het geval, maar dateert men in dergelijke gevallen een andere (voorafgaande) constructie.
