# Sporenkappen van onzekere typologie

## Jan van Eyckplein 8, Huis *De Roode Steen*

Dit bakstenen huis was aan de drie straatgevels voorzien van zeven waterlijsten in Doornikse steen waarvan slechts enkele verspreide fragmenten bewaard bleven[^onzekeretypologie-1]. De huidige dakconstructie dateert uit het midden van de 15de eeuw (zie 8.2.6, fig. 67) maar bevat veel hergebruikt hout uit een oudere sporenkap. De oude daksporen hebben een uitgesproken rechthoekige sectie en elk sporenpaar was verstevigd door twee halfhouts verbonden hanenbalken. Op basis van het bewaarde materiaal lijkt het zeer waarschijnlijk dat deze oude kap een sporenkap was.

[^onzekeretypologie-1]: Voor een volledig overzicht van de bouwgeschiedenis zie Van Eenhooge 2007, 25-30. Huis *De Roode Steen* in de inventaris van het bouwkundig erfgoed: <https://inventaris.onroerenderfgoed.be/erfgoedobjecten/29365>.

De zeven stalen die uit dit hergebruikmateriaal werden genomen leverden een curve op waaruit een gemiddelde kon worden berekend. Vergelijking met de referentiekalenders laat toe de jongste gemeten jaarring in 1224d te dateren. Dit betekent dat, na toevoeging van het geschatte aantal ontbrekende jaarringen, het vellen van de bomen moet worden gesitueerd tussen 1225 en 1240d[^onzekeretypologie-2].

[^onzekeretypologie-2]: Eeckhout & Houbrechts 2002, 19-22.

## Stadhuis van Brugge

De 14de-eeuwse kap van het stadhuis (zie 9.2) bevat veel hergebruikte onderdelen[^onzekeretypologie-3]. De inkepingen op sommige hanenbalken tonen aan dat zij oorspronkelijk daksporen waren waarin hanenbalken waren ingelaten. Bij de dendrochronologische analyse bleek bovendien dat een aantal standzonen eveneens afkomstig waren uit een oudere kap. De drie stalen die tot deze groep behoren konden samengevoegd worden tot een 173 jaar lange middelcurve. Vergelijking met de referentiekalenders laat toe de jongste gemeten jaarring in 1218d te dateren. Dit betekent dat, rekening houdend met het geschatte aantal ontbrekende jaarringen, het vellen van de bomen tussen 1226 en 1244d moet worden gesitueerd[^onzekeretypologie-4].

[^onzekeretypologie-3]: Het stadhuis in de inventaris van het bouwkundig erfgoed: <https://inventaris.onroerenderfgoed.be/erfgoedobjecten/29238>.

[^onzekeretypologie-4]: Haneca 2014a.

De 13de-eeuwse balken zijn misschien afkomstig van het *Ghyselhuus*, de grafelijke gevangenis die in de jaren 1370 werd afgebroken om plaats te maken voor het huidige stadhuis[^onzekeretypologie-5].

[^onzekeretypologie-5]: Gilté & Vanwalleghem 1999, 37.

## Vlamingstraat 82

De 13de-eeuwse oorsprong van dit huis is duidelijk aan de achterzijde waar muurfragmenten in het baksteenformaat 30 x 8 cm bewaard is[^onzekeretypologie-6]. De dakkap is een 18de-eeuwse gordingenkap met schaar- en nokstijlgebinten. Een groot aantal kepers hebben een uitgesproken rechthoekige doorsnede (19 x 9 cm) en vertonen inkepingen voor telkens twee halfhouts verbonden hanenbalken. Deze sporen laten minstens de reconstructie toe van een sporenkap met twee hanenbalken per sporenpaar. Al blijft het onduidelijk of er een langsverbinding was of niet.

[^onzekeretypologie-6]: Vlamingstraat 82 in de inventaris van het bouwkundig erfgoed: <https://inventaris.onroerenderfgoed.be/erfgoedobjecten/29914>.

## Vlamingstraat 45

Dit diephuis is met een maximale lengte van 23,6 m en een breedte van 7,95 m één van de grootste middeleeuwse bakstenen huizen in Brugge[^onzekeretypologie-7]. De oorspronkelijke kapconstructies zijn verdwenen, maar in de waarschijnlijk 18de-eeuwse dakkap van het voorhuis behoren een groot aantal kepers tot een middeleeuwse sporenkap. Hoogstwaarschijnlijk betrof het een sporenkap met twee halfhouts verbonden hanenbalken per sporenpaar. Op enkele sporen is duidelijk dat er aan de buitenkant een schuine windlat op bevestigd was.

[^onzekeretypologie-7]: Vlamingstraat 45 in de inventaris van het bouwkundig erfgoed: <https://inventaris.onroerenderfgoed.be/erfgoedobjecten/29903>.

Onderzoek van de originele sporen toonde aan dat het ging om eikenhout met een snelle groei die een goed dendrochronologisch resultaat in de weg stond. Er werden geen stalen genomen.

## Vlamingstraat 17, ambachtshuis van de Kuipers

De oudste bouwfase van dit huis is enkel in de kelder bewaard gebleven[^onzekeretypologie-8]. De afmetingen van de bakstenen (29 x 6 cm) laten toe om de oorspronkelijke kern van het pand te dateren in ongeveer 1260-1300. Metselwerk in bakstenen van 26 x 6 cm suggereren een verbouwing van het huis in het eerste derde van de 14de eeuw. Het huis, dat in de 14de eeuw bekend was als *Den Baers*, staat op de kaart van Marcus Gerards uit 1562 afgebeeld met een hoge schermgevel met arkeltorentjes. Het pand werd ingrijpend verbouwd in 1768. De bestaande dakkap dateert uit deze periode maar bevat veel hergebruikmateriaal uit oudere sporenkappen. De sporen hebben een doorsnede van 10 x 10 cm maar de overgrote meerderheid is uitgesproken rechthoekig (9 x 12 cm of 10 x 14 cm). Elk sporenpaar was voorzien van twee halfhouts verbonden hanenbalken die met één toognagel waren vastgezet.

[^onzekeretypologie-8]: Het ambachtshuis van de kuipers in de inventaris van het bouwkundig erfgoed: <https://inventaris.onroerenderfgoed.be/erfgoedobjecten/29887>.

## Hoogstraat 25, huis *de biekorf*, nadien *de kroon*

Het oorspronkelijke huis uit het einde van de 13de eeuw, gebouwd in baksteen van het formaat 29 x 6,5 cm, omvatte het hoekhuis Ridderstraat 21 en het pand in de Hoogstraat[^onzekeretypologie-9]. De rechter zijgevel van Hoogstraat 25 is nog grotendeels oorspronkelijk en vertoont nu dichtgemaakte vensteropeningen in spitsboog- of driepasnissen ter hoogte van de zolder. De bestaande kapconstructie (10.2.10) bevat hergebruikmateriaal dat waarschijnlijk afkomstig is van de oorspronkelijke sporenkap: zeven zware daksporen met een rechthoekige sectie (7 x 14 cm, 9 x 16 cm, 11 x 18 cm en 9,5 x 20 cm) en inkavelingen van twee halfhouts verbonden hanenbalken.

[^onzekeretypologie-9]: Huis *De Biekorf* in de inventaris van het bouwkundig erfgoed: <https://inventaris.onroerenderfgoed.be/erfgoedobjecten/29348>.

Uit de vermelde daksporen werden vijf boorkernen genomen, die samen een middelcurve vormen waarvan de jongste jaarring dateert uit 1275d. Bij twee van de onderzochte boorkernen was de wankant aanwezig, wat toelaat de veldatum te situeren in de maand april of mei van 1275d[^onzekeretypologie-10].

[^onzekeretypologie-10]: Haneca 2014b.

## Grauwwerkersstraat 6

De bestaande kap van het huis kwam duidelijk tot stand door de verbouwing van een oudere kap (10.1.12)[^onzekeretypologie-11]. In deze oude kap hebben de daksporen een sectie van 10 x 15 cm, en was elk sporenpaar voorzien van twee halfhouts verbonden hanenbalken. Er waren blijkbaar geen standzonen of korbelen.

[^onzekeretypologie-11]: Grauwwerkersstraat 6 in de inventaris van het bouwkundig erfgoed: <https://inventaris.onroerenderfgoed.be/erfgoedobjecten/29317>.
