# Bibliografie

Beernaert B., Delfosse J. & De Meester T. 2007: *Zeven eeuwen stadsgeschiedenis in een huis. Bewonings- en bouwgeschiedenis van het huis Gouden-Handstraat 21 in Brugge*, Brugge.

Buyle M. 1995: Een puzzel op de schouw en draken op de muren. Merkwaardige muurschilderingen uit de late 14de eeuw in een Brugs woonhuis, *M&L. Monumenten & Landschappen* 14.1, 6-27.

Coomans T. 2006: De oudste dakconstructie in de Leuvense binnenstad: bouwhistorisch onderzoek in de predikherenkerk (prov. Vlaams-Brabant), *Relicta. Archeologie, Monumenten- en Landschapsonderzoek in Vlaanderen* 1, 183-212.

Coomans T. & Van Eenhooge D. 2005: De 13de-eeuwse oostvleugel van het Predikherenklooster te Leuven, *M&L. Monumenten & Landschappen* 24.5, 35-50.

de Vries Dirk J. 2000: Vergelijkend natuurwetenschappelijk onderzoek, *Bulletin van de Koninklijke Nederlandse Oudheidkundige Bond* 99.3, 74-84.

De Witte H. 2000: Sint-Janshospitaal. In: *Stad Brugge, Stedelijke Musea. Jaarboek 1997-99*, Brugge, 139-146.

Debonne V. 2015: *Uit de klei, in verband. Bouwen met baksteen in het graafschap Vlaanderen 1200-1400*, doctoraatsverhandeling, KU Leuven, Faculty of Engineering Science, Leuven.

Debonne V. 2016: *Brugge, Sint-Gilliskerk. Bouwhistorisch onderzoek van de dakkap (prov. West-Vlaanderen)*, Onroerend Erfgoed - Rapporten Bouwhistorisch Onderzoek OE-RBO 2015-002, Brussel.

Debonne V. & Haneca K. 2011: Baksteen en boomringen: een verfijnde bouwchronologie van het hallenkoor van de Onze-Lieve-Vrouwkerk in Damme (prov. West-Vlaanderen), *Relicta. Archeologie, Monumenten- en Landschapsonderzoek in Vlaanderen* 7, 67--100.

Devliegher L. 1954: De opkomst van de kerkelijke gotische bouwkunst in West-Vlaanderen. *Bulletin van de Koninklijke Commissie voor Monumenten en Landschappen* 5, 177-345.

Devliegher L. 1956: De opkomst van de kerkelijke gotische bouwkunst in West-Vlaanderen gedurende de XIIIe eeuw. *Bulletin van de Koninklijke Commissie voor Monumenten en Landschappen* 7, 9-121.

Devliegher L. 1957: De vroegste gebouwen van baksteen in Vlaanderen, *Bulletin van de Koninklijke Nederlandse Oudheidkundige Bond* 10.6, 245-250.

Devliegher L. 1965a: *Beeld van het kunstbezit*, Kunstpatrimonium van West-Vlaanderen 1, Tielt - Den Haag.

Devliegher L. 1965b: De bouwrekeningen van het stadhuis te Damme, *Handelingen Genootschap voor Geschiedenis 'Société d'Émulation' te Brugge* 102, 134-202.

Devliegher L. 1971: *Damme*, Kunstpatrimonium van West-Vlaanderen 5, Tielt -- Utrecht.

Devliegher L. 1975²: *De huizen te Brugge*, Kunstpatrimonium van West-Vlaanderen 2-3, Tielt -- Utrecht (tweede herziene uitgave).

Devliegher L. 1981: *De Sint-Salvatorskathedraal te Brugge. Geschiedenis en architectuur*, Kunstpatrimonium van West-Vlaanderen 7, Tielt -- Utrecht.

Devliegher L. 1987: *De Keizer Karel-schouw van het Brugse Vrije*, Kunstpatrimonium van West-Vlaanderen 10, Tielt.

Devliegher L. 1994: *Behoedzaam Omgaan, Monumentenzorg in Brugge 1988/1993,* Brugge.

Devliegher L. 1997: De bouwgeschiedenis van de kerk. In: De Smaele H., Flour E., Heyndrikx V. & De Jonghe M. (reds.), *De Onze-Lieve-Vrouwekerk te Brugge. Kunst & geschiedenis*, Brugge, 1997, 99-108.

Devliegher L. & Didier R. 1986: *Dertiende-eeuwse houtsculptuur in de Onze-Lieve-Vrouwekerk te Damme*, Damme.

Eeckhout J. 2006: *Fiche d'analyse dendrochronologique, Eglise Notre-Dame à Bruges*, onuitgegeven onderzoeksrapport, Université de Liège, Laboratoire de dendrochronologie, Luik.

Eeckhout J. & Galand A. 2005: *L'église Notre-Dame à Bruges*, onuitgegeven onderzoeksrapport Université de Liège, Laboratoire de dendrochronologie, Luik.

Eeckhout J. & Hoffsummer P. 2006: *Eglise Notre-Dame à Bruges. Fiche d'analyse dendrochronologique*, Laboratoire de dendrochronologie, Université de Liège, Luik.

Eeckhout J. & Houbrechts D. 2002: *Charpentes et caves médiévales à Bruges; campagne d'analyses 2001-2002*, onuitgegeven onderzoeksrapport Université de Liège, Laboratoire de Dendrochronologie, Luik.

Eeckhout J. & Houbrechts D. 2004: *Hôpital Saint-Jean à Bruges, Dortoir des Pères*, onuitgegeven onderzoeksrapport, Université de Liège, Laboratoire de dendrochronologie, Luik.

Eeckhout J. & Houbrechts D. 2006: *De bekappingen van de Hallen in Brugge*, onuitgegeven onderzoeksrapport, Université de Liège, Laboratoire de dendrochronologie, Luik.

Épaud F. 2007: *De la charpente romane à la charpente gothique en Normandie. Évolution des techniques et des structures de charpenterie aux XII^e^-XIII^e^ siècles*, Caen.

Esther J. 1976: Monumentenbeschrijving en bouwgeschiedenis. In: *Sint-Janshospitaal Brugge 1188/1976*, dl. 1, Brugge, 259-339.

Esther J. \[1994\]: *Restaureren/Renoveren,* N.V. Arthur Vandendorpe*,* Brugge.

Fraiture P. 2002: *Maison sis Jan van Eyckplein 8, lambris de plafond*, onuitgegeven onderzoeksrapport, Université de Liège, Laboratoire de dendrochronologie, Luik.

Gilté S. & Vanwalleghem A. 1999: *Stad Brugge, oudste kern*, Bouwen door de eeuwen heen. Inventaris van het cultuurbezit in België. Architectuur 18n a, Turnhout.

Gilté S. & Vanwalleghem A. 2004a: *Stad Brugge, middeleeuwse stadsuitbreiding, zuid*, Bouwen door de eeuwen heen. Inventaris van het cultuurbezit in België. Architectuur 18n b, Turnhout.

Gilté S. & Vanwalleghem A. 2004b: *Stad Brugge, middeleeuwse stadsuitbreiding, noord*, Bouwen door de eeuwen heen. Inventaris van het cultuurbezit in België. Architectuur 18n b, Turnhout.

Gysseling M. (ed.) 1977: *Corpus van Middelnederlandse teksten (tot en met het jaar 1300). Reeks I: Ambtelijke bescheiden*, 15 dln., 's-Gravenhage.

Haneca K. 2005: *Tree-ring analyses of European oak: implementation and relevance in (pre-)historical research in Flanders,* doctoraatsverhandeling, Universiteit Gent, Faculteit bio-ingenieurs-wetenschappen, Gent.

Haneca K. 2007: *Verslag dendrochronologisch onderzoek: dakgebinte noordbeuk van de Sint-Jacobskerk te Brugge*, Universiteit Gent, Laboratorium voor houttechnologie, Rapport HT07-0910, Gent.

Haneca K. 2011: *Balk uit woonhuis Genthof 33 te Brugge*, Rapporten natuurwetenschappelijk onderzoek VIOE, 2011-007, Brussel.

Haneca K. 2012: *Verslag dendrochronologisch onderzoek. Kappen van de Sint-Gilliskerk te Brugge (prov. West-Vlaanderen)*, Rapporten natuurwetenschappelijk onderzoek Onroerend Erfgoed, 2012-012, Brussel.

Haneca K. 2014a: *Verslag Dendrochronologisch onderzoek. Dakkap van het stadhuis van Brugge,* Rapporten natuurwetenschappelijk onderzoek Onroerend Erfgoed, 2014-018, Brussel.

Haneca K. 2014b: *Verslag dendrochronologisch onderzoek. Dakkap van huis De Biekorf, Hoogstraat 25 te Brugge,* Rapporten natuurwetenschappelijk onderzoek Onroerend Erfgoed, 2014-015, Brussel.

Haneca K. 2014c: *Verslag dendrochronologisch onderzoek. Dakkap van burgerhuis De Matte, Philipstockstraat 3 te Brugge*, Rapporten natuurwetenschappelijk onderzoek Onroerend Erfgoed, 2014-016, Brussel.

Haneca K. 2014d: *Verslag dendrochronologisch onderzoek. Dakkap van een breedhuis aan Begijnhof 50 te Brugge,* Rapporten natuurwetenschappelijk onderzoek Onroerend Erfgoed, 2014-014, Brussel.

Haneca K. 2014e: *Verslag dendrochronologisch onderzoek. Dakkappen van Huis Ieper, Kraanplein 6 te Brugge,* Rapporten natuurwetenschappelijk onderzoek Onroerend Erfgoed, 2014-017, Brussel.

Haneca K. 2014f: *Verslag dendrochronologisch onderzoek. Dakkap van Huis Adornes, Peperstraat 1-3 te Brugge,* Rapporten natuurwetenschappelijk onderzoek Onroerend Erfgoed, 2014-012, Brussel.

Haneca K. 2014g: *Verslag dendrochronologisch onderzoek. Dakkap van Hof Bladelin, Naaldenstraat 21 te Brugge,* Rapporten natuurwetenschappelijk onderzoek Onroerend Erfgoed, 2014-013, Brussel.

Haneca K. 2014h: *Verslag dendrochronologisch onderzoek. Dakkap van burgerhuis Het Schietspel, Sint-Jakobsstraat 64 te Brugge,* Rapporten natuurwetenschappelijk onderzoek Onroerend Erfgoed, 2014-019, Brussel.

Haneca K. 2016*:* Verslag dendrochronologisch onderzoek. Dakkap en balklaag van het diephuis aan het Kraanplein 4 te Brugge, Rapporten natuurwetenschappelijk onderzoek Onroerend Erfgoed, 2016-013, Brussel.

Haneca K. 2017: Dendrochronologie en erfgoedonderzoek, Handleidingen agentschap Onroerend Erfgoed Brussel 16 \[online: <https://oar.onroerenderfgoed.be/publicaties/HAOE/15/HAOE016-001.pdf>\].

Haneca K. & Debonne V. 2012: Precise tree-ring dating of building activities despite the absence of bark: A case-study on medieval church roofs in Damme, Belgium, *Dendrochronologia* 30.1, 23--34.

Hanraets E. 2000: *Rapportage daterend onderzoek. Brugge, Sint-Janshospitaal*, RING Intern Rapport (juli 2000), Amersfoort.

Haslinghuis E.J. 2005^5^: *Bouwkundige termen. Verklarend woordenboek van de westerse architectuur- en bouwgeschiedenis*, 5de druk, Leiden.

Hoffsummer P. 2002: *Les charpentes du XIe au XIX siècle. Typologie et évolution en France du Nord et en Belgique*, Cahiers du Patrimoine 62, Paris.

Hoffsummer P. (ed.) 2009: *Roof frames from the 11th to the 19th century: Typology and development in Northern France and in Belgium*, Architectura Medii Aevi 3, Turnhout.

Janse H. 1989: *Houten kappen in Nederland 1000-1940*, Bouwtechniek in Nederland 2, Delft -- Zeist.

Janse H. & Devliegher L. 1962: Middeleeuwse bekappingen in het vroegere Graafschap Vlaanderen, *Bulletin van de Koninklijke Commissie voor Monumenten en Landschappen* 13, 299-380.

Nuytten D. 2005: Bouwhistorisch onderzoek van de voormalige abdijschuur van Ter Doest, *Bulletin van de Koninklijke Nederlandse Oudheidkundige Bond* 104.2-3, 58-74.

Sapin C. (dir.) 2011: *Saint-Etienne d'Auxerre, la seconde vie d'une cathédrale. 7 ans de recherches pluridisciplinaires et internationales*, Auxerre - Parijs.

van der Hoeve J. 2014: *Brugge, St. Jacobskerk. Bouwhistorische waarnemingen*, Bureau voor bouwhistorisch onderzoek J.A. van der Hoeve, Utrecht.

Van Eenhooge D. 2001: The archaeological study of buildings and town history in Bruges. Domestic architecture in the period 1200-1350. In: Gläser M. (ed.), *Lübecker Kolloquium zur Stadtarchäologie im Hanseraum III: Der Hausbau*, Lübeck, 121-142.

Van Eenhooge D. 2002a: Twee 13de-eeuwse domeinen in de Sint-Jansstraat te Brugge, *Brugs Ommeland* 3, 139-162.

Van Eenhooge D. 2002b: Middeleeuwse Brugse huizen :bouwhistorisch onderzoek in de huizen in Sint-Jacobs en den Ancker, *M&L. Monumenten & Landschappen* 21.5, 44-61.

Van Eenhooge D. 2002c: Middeleeuwse Brugse huizen: bouwhistorisch onderzoek in de Florentijnse loge en het huis Hertsberghe in de Academiestraat, *M&L. Monumenten & Landschappen* 21.4, 32-45.

Van Eenhooge D. 2006: Middeleeuwse Brugse huizen: het Heylich Graf, het Pijndershuisje, de Grote Tol en het Wezelkin aan het Jan van Eyckplein, *M&L. Monumenten en Landschappen* 25.1, 29-42.

Van Eenhooge D. 2007: Middeleeuwse Brugse huizen en hofsteden langs de Spiegelrei, *M&L. Monumenten, Landschappen & Archeologie* 26.5, 22-44.

Van Eenhooge D. 2009: De middeleeuwse sporenkappen van de Onze-Lieve-Vrouwekerk in Brugge, *M&L. Monumenten, Landschappen & Archeologie* 28.2, 21-45.

Van Strydonck M. 1994: *Radiocarbon Dating Report IRPA-1019*, onuitgegeven onderzoeksrapport KIK-IRPA, Brussel.

Verhaegen A. 1889: *L'hôpital de la Byloke, à Gand/De Bijloke van Gent*, Provinciale Kommissie der praalgebouwen van Oost-Vlaanderen, Gent.
